apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo
  labels:
    app: cicd-demo
spec:
  selector:
    matchLabels:
      app: cicd-demo
  replicas: 1
  template:
    metadata:
      name: cicd-demo
      labels:
        app: cicd-demo
    spec:
      containers:
        - name: cicd-demo
          image: local/cicd-demo:latest # Image that will be used inside the container in the cluster
          imagePullPolicy: Never
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-demo
  labels:
    app: cicd-demo
spec:
  type: NodePort
  selector:
    app: cicd-demo
  ports:
    - name: http
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080